### ISSUE TITLE
Empty the Armory : create feature and achievement

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitrpg#7991]
Now that the [Orb of Rebirth no longer removes equipment](https://github.com/HabitRPG/habitrpg/issues/7917), we need a similar feature that does remove gear (but does nothing else).

Features:
- [ ] The name for it is tentatively *"Empty the Armory"* but other suggestions are welcome.
- [ ] It will cost 2 gems.
- [ ] For players who are at or above level 100, it will be free.
- [ ] It will not remove gear that costs zero gold (because it's trivial to "buy" back so there's no point removing it).
- [ ] It must not reintroduce this bug: [Orb of Rebirth causes animal ears in 'Customize Avatar' interface to need to be repurchased](https://github.com/HabitRPG/habitrpg/issues/7662)
- [ ] It must have its own "Empty the Armory" achievement, which increases by one each time the emptying is done (works a similar way as `achievements.rebirths`).
- [ ] **For discussion**: We need to decide when the Empty the Armory feature becomes unlocked. At level 50? After receiving one Ultimate Gear achievement? **Suggestions welcome.**
- [ ] **For discussion**: We need to decide if the achievement increases by one only if you use the Empty the Armory feature at the same level or higher than previously (as is done for the Rebirth achievement). **Suggestions welcome.**
- [ ] [Artwork is being created for the achievement badge](https://trello.com/c/xfXldYs1/11-badges-open). Until it's ready, I suggest creating a placeholder image using a copy of the Orb's badge.
Disagreements welcome.
- [ ] I suggest that the achievement should not cause an increase in the player's drop chance (an increase is caused by Rebirth), because drop chances already have quite a few boosting events for long-term users. Disagreements welcome.
- [ ] The Seasonal Shop displays the `seasonalShopRebirth` message ("If you've used the Orb of Rebirth, you can repurchase this equipment in the Rewards Column...."). That message should be changed to mention the Empty the Armory feature as well as the Orb (rebirth should remain in that message for a while, for the benefit of players who rebirthed before it was nerfed).
- [ ] `settings.json` contains `resetText2` which ends with "You might prefer to use an Orb of Rebirth instead, which is a much safer option and which will preserve your tasks.". That should be changed to say "... and which will preserve your tasks and your equipment."  We should have made that change in #7917 but we overlooked it.

Much of the code for this new feature will be similar to code for the original Rebirth feature, so here's some links to **some** of the relevant files from the production website release from before Rebirth was nerfed:
- https://github.com/HabitRPG/habitrpg/blob/31a1a14baecb464e66c94d259cbac9cdcbbc7e89/website/views/shared/modals/rebirth.jade
- https://github.com/HabitRPG/habitrpg/blob/31a1a14baecb464e66c94d259cbac9cdcbbc7e89/common/locales/en/rebirth.json
- https://github.com/HabitRPG/habitrpg/blob/31a1a14baecb464e66c94d259cbac9cdcbbc7e89/common/script/ops/rebirth.js
- https://github.com/HabitRPG/habitrpg/blob/31a1a14baecb464e66c94d259cbac9cdcbbc7e89/test/api/v3/integration/user/POST-user_rebirth.test.js
- https://github.com/HabitRPG/habitrpg/blob/31a1a14baecb464e66c94d259cbac9cdcbbc7e89/test/common/ops/rebirth.js

**Actions for staff/admins after a contributor has created this feature:**
- [ ] Write a Bailey message to introduce the feature and to say that all players who obtained Orb of Rebirth achievement(s) before 11 September (when the Orb was nerfed) have been given the same number of Empty the Armory achievements (in addition to keeping their Rebirth achievements).
- [ ] Give the Empty the Armory achievement to those players. Alys has a list.
- [ ] Ask the wiki editors to adjust the Start Over Options page, as well as adding a new page for this new feature.

_I'm marking this issue as both help welcome and for suggestion/discussion, because a coder could start on most of it while we're deciding on the final details of some of the points listed here._

**Comment by khipkin** [comment]
I think new achievements should wait until the following things are resolved (issues closed & PRs merged into develop):

- [ ] Issue #7946 _(Notifications no longer work.)_
- [ ] PR #7904 _(Achievement list visual revamp & Achievements API)_

Absolutely minimally, the second one (the PR), because it will remove all achievements-related code except for updating the achievements object returned by the API.

**Comment by khipkin** [comment]
But I would be interested in adding the feature!

**Comment by lemoness** [comment]
The badge art is ready! https://trello-attachments.s3.amazonaws.com/52e9d25cd467121630c6350d/52e9d76055a08df534a7aa7f/c3bc646a80f41e47a81b117a2dab2775/empty_as_heckums.png

**Comment by lynxlynxlynx** [comment]
I'm just noting that since the rewrite, rebirth is not displaying that seasonalShopRebirth string: https://github.com/HabitRPG/habitica/blob/009ab26711e5d8cdbd5da2fbc14a42789c538259/website/views/options/inventory/seasonal-shop.jade#L11

**Comment by crookedneighbor** [comment]
That's intentional. The code has been rewritten to only show items that can be purchased, so the string should be unnecessary now.

**Comment by lynxlynxlynx** [comment]
I know, but the OP todo list still mentions it as it was.

**Comment by Alys** [comment]
@lynxlynxlynx Thank you! I've edited the OP.

**Comment by khipkin** [comment]
The PR I mentioned above (#7904) has finally been merged, so I can start working on this sometime this week! 🎉

**Comment by beffymaroo** [comment]
An artisan is now working on an item to put in the Market (akin to Key to the Kennels) for this feature. The info for badge name/ mouseover text is as follows: 

> Empty the Armory 
> Has collected all the gear for at least one class and has emptied their armory X time(s).


If possible it could also say how many classes they have Ultimate Gear for?

**Comment by Alys** [comment]
@beffymaroo So the message should be:
"Has collected all the gear for 1 class(es) and has emptied their armory X time(s)."
"Has collected all the gear for 2 class(es) and has emptied their armory X time(s)."
and the same for 3 and 4 classes. Yes? That's achievable.

**Comment by lemoness** [comment]
I just wanted to note that the art work for the Armory Key is done, designed by the wonderful PainterProphet! I'm attaching it to this Github ticket.
![armory_key_v2](https://cloud.githubusercontent.com/assets/3494081/26020669/59c7bdac-3736-11e7-9ce8-a5e4d1e3588f.png)

**Comment by khipkin** [comment]
This can be put up for grabs again. Sorry I never got to it!

**Comment by Alys** [comment]
@khipkin No worries! Thanks for letting us know!

**Comment by megan-starr9** [comment]
I wouldn't mind taking a look at this!

**Comment by Alys** [comment]
@megan-starr9 Great, thanks! If you have questions or run into trouble, post here.

**Comment by megan-starr9** [comment]
Will do, thanks a bunch!

**Comment by brightbold** [comment]
I'm excited for this feature! A suggestion for discussion: Could we have an option to also empty the zero GP items (the way Keys to the Kennel lets you choose pets, mounts, or both)? I'm very motivated by equipment, and felt disappointed when I'd run out of standard gear to buy. So when I did my last rebirth (back when the Orb removed equipment), I created more challenge by forcing myself to pay (via custom rewards) to buy back the free items. Since there are a lot of those, it significantly increased the length of time I was able to use gear to motivate me to get more done. I'd love to be able to do this again.

**Comment by lemoness** [comment]
I think that could be a viable option for a future version of this feature,
but shouldn't hold up the initial release.

**Comment by Alys** [comment]
If we do implement the option to remove free gear (I agree that we should when we have time), then we'll need to make an adjustment to the `back_special_snowdriftVeil` item, and possibly the other items given in check-in incentives. Recently, I removed all gear for Il Mago Rosso, and we found that the Snowdrift Veil didn't appear in the Rewards column to be bought back, possibly because we've never bothered making the check-in incentive gear purchasable since there's currently no official way that they can be lost (zero-cost items are never removed by Death). I've fixed the problem for  Il Mago Rosso and I haven't bothered looking into this in detail since it could be months before it becomes a real issue.

@brightbold If you want your gear removed so you can buy it back, drop in to the Report a Bug guild to request it. Even though that isn't a bug, it's good to ask there because it needs help from an admin. I have a script to do it so it only takes me a minute.

**Comment by brightbold** [comment]
@Alys Ooh thanks! I will take you up on that — I'm about to do a rebirth and I like to return to powerless and possessionless baby adventurer and have to build from the ground up. I really appreciate it!

**Comment by MathWhiz** [comment]
@megan-starr9 Are you still working on this?

**Comment by lemoness** [comment]
I've updated the labels.

**Comment by megan-starr9** [comment]
Sorry!! I meant to respond the other day - that’s fine though! I’m familiar with angular, not vue, so the change in platform slowed me down some.

**Comment by MathWhiz** [comment]
@megan-starr9 Do you need any help with this?

**Comment by lemoness** [comment]
This is now open for someone to work on again!

**Comment by TheHollidayInn** [comment]
Thanks for the feedback :D We haven't discussed this in a while, but I'll pass your questoins on when we discuss.

**Comment by Ieahleen** [comment]
I think mystery items are between those with a 0 gold cost so are not affected by this, but if you loose from death previous galas gear, equipment from quests or contributors gear,they have a gold price so they can be bought back (or for quest gear regained doing the quest)

**Comment by citrusella** [comment]
My brain has decided to detail what I remember of losing gear through rebirth: Previously, you wouldn't lose mystery gear at all IIRC, but maybe it was in the rewards column for zero gold? (Or maybe that was just the one time Alys wiped my equipment after I missed the end of the window for "traditional" rebirth?) Gala gear technically would require gems or a rebirth if you wanted it from a class you aren't... but that's true of *all* class gear and they do otherwise cost gold. Contributor gear never cost gems, AFAIK, but it does have a gold cost, IIRC. Quest and armoire gear have two ways of being gotten back (directly from the rewards or via the quest/armoire).

**Comment by brightbold** [comment]
As in citrusella's case, Alys offered to wipe all my equipment post-rebirth because I wanted the challenge of buying it all back, and she did it for me at the beginning of this year (so the below was true as of January). All equipment has been available in the store either for gold (regular gear, quest items, gala gear, previously owned Enchanted Armoire items, and contributor rewards) or for free (subscriber gear, Habitica party robes/hats, special edition conference items, Gaymer X armor, Take This gear). I think that covers every type of gear except Kickstarter (which presumably would work the same way, but it's the one type I can think of that I can't confirm). So it seems like there aren't any equipment types that become lost.  

FWIW, Gala gear shows up in the market with the clock icon indicating that it's only available during its gala season, but you can actually buy the previously owned gala gear at any time.

Also, citrusella is correct that in oldschool rebirth, all the mystery items showed up in your rewards column for zero gold. Which was annoying and cluttered up your tasks page, so I like the new system of having them in the shop much better.

**Comment by citrusella** [comment]
I believe backer gear (and the critical hammer of bug crushing, to be complete) probably ends up in the gear to buy back, too, considering the equipment table (which I think is generated from Habitica's code?) lists both things as having an actual price, which must theoretically means they can be bought... though I can't confirm either, either.

~~I liked having an ultra long list of gear to buy. I think that was the *most* motivating to me. XD~~

**Comment by Alys** [comment]
@Joseph67843  As others have said, currently in Habitica whenever you have previously obtained a piece of equipment using either gold or gems or been given it for free, you can **always** get it back (even gear that's no longer available to anyone else), and you can always get it back without using gems (it will be either free or will cost gold). Note that for class-specific gear you will need to be the correct class before you can buy it back for gold (changing class can be done for free if you use an Orb of Rebirth at or after level 100). I imagine that this Empty the Armory feature would work exactly the way that the Orb of Rebirth worked when it used to remove gear, and so buying back with gold will be possible for everything you used to own.

In case anyone here is curious about the technical aspects of this, when you obtain a gear piece, it's added to you account with a "true" value. When you lose it (via any method), it remains in your account with a "false" value - that's how Habitica knows to not show it to you as a piece you own but to allow you to buy it with gold.
Gear that you have never owned is not stored in your account at all (neither true nor false, just missing).

To answer the specific questions:

_"Previously, you wouldn't lose mystery gear at all IIRC, but maybe it was in the rewards column for zero gold? (Or maybe that was just the one time Alys wiped my equipment after I missed the end of the window for 'traditional' rebirth?)"_

Back in the very old days as @brightbold says, you could lose Mystery Gear (and get it back by "buying" it for zero gold) but after a while we changed that so it wasn't removed by Rebirth (and of course now no gear is removed by Rebirth). It's entirely possible that my manual fix did not do exactly the same thing that the real Rebirth used to do. :)

_"Contributor gear never cost gems, AFAIK, but it does have a gold cost, IIRC."_

Correct (200 Gold).

_"Kickstarter (which presumably would work the same way, but it's the one type I can think of that I can't confirm)."_
_"I believe backer gear (and the critical hammer of bug crushing, to be complete) probably ends up in the gear to buy back, too"_

That's correct - you can buy them back with Gold (150 to 200 Gold).

_"the equipment table (which I think is generated from Habitica's code?) "_

Yes, it is. The [Equipment Table](https://habitica.wikia.com/wiki/Equipment_Table) is created with the [Habitica Wiki Equipment Table Creator](http://oldgods.net/habitica/equipment_table_creator.html), which uses Habitica's API to fetch the official data for all the gear.

_"FWIW, Gala gear shows up in the market with the clock icon indicating that it's only available during its gala season, but you can actually buy the previously owned gala gear at any time."_

Oh yeah, we really should get that fixed. The clock should not appear in that case. We don't see to have an issue for it (I think it was mentioned in other issues, now closed) so I'll create a new one this weekend. Thanks for mentioning it. :)

Also, in case anyone is curious and because this is loosely related, when Death happens, you cannot lose any class-specific equipment for a different class than the one you are currently playing (in the very old days, it used to be that you could lose off-class gear, but we changed that). Death will also never remove free equipment because subscribers have much more free gear than other players (Mytery Items) and so if Death included free gear, subscribers would have a much higher chance of losing free gear when they Died, meaning that they would have an advantage over free players (and Habitica avoids being "pay to win").

**Comment by Alys** [comment]
Ooo, I missed this:
_I liked having an ultra long list of gear to buy. I think that was the most motivating to me. XD"_

I still have my script to remove ALL gear. I can run it whenever you like. :)

**Comment by brightbold** [comment]
> I liked having an ultra long list of gear to buy. I think that was the most motivating to me. XD
To be clear, I liked that too! Enough that I asked Alys to run her script on me, and 8 months later I'm still working hard to earn gold to buy back all that gear. (I use custom rewards to pay market price for the free gear, so it's taking a while!) I just like it much better now that it's on the Market page, where I can decide what I most want to earn gold for next and pin those items to the Tasks page, than when it was all on the Tasks page where it couldn't be filtered or sorted.

**Comment by Arsnael** [comment]
@Alys : I will if I need to, thanks :)

**Comment by Alys** [comment]
@Arsnael  Any item that costs zero gold should not be removed by Empty the Armory - you can identify those items by them having a `value` of `0`. For example:
https://github.com/HabitRPG/habitica/blob/1b3dad749e8beef3289e8c564703701b1bc21c02/website/common/script/content/gear/sets/special/index.js#L1193-L1198

Any equipment piece with a `value` greater than zero should be removed (i.e., Empty the Armory will set it to `false` in the player's `items.gear.owned` object). The player will be able to buy back all of those items using gold (the `value` indicates the amount of gold), so removing them is the desired behaviour.

Some of those "value > 0" pieces would originally have been bought using Gems (e.g., the Animal Tails) but you can ignore that. The method that the player first uses to obtain an equipment piece is irrelevant after the initial purchase, because once you've bought an equipment piece, you can always rebuy it with gold no matter how you lose it (although of course for gear belonging to classes other than yours, you have to change to that class first).

> it seems rebirth resets the tasks right? I guess Empty the armory shouln't, correct?

Correct. Empty the Armory affects only equipment.

**Comment by Arsnael** [comment]
alright thanks @Alys :)

**Comment by Alys** [comment]
@beffymaroo ^^

**Comment by Arsnael** [comment]
So I'm starting going on the same basics as rebirth, as to know lvl 50 available for 2 gems, lvl 100 free... Might need to think about other criterias though, it could be abused depending what you want to do with the counter of the achievement. Like if it's just a matter of levels, the user could abuse it in resetting and making the counter go up... (not that it might be useful, but well...). The other way around works too... Imagine the user just did a rebirth, and then thinks "oh damn I wanted to reset my armory too... oh but I'm back at lvl1 I cannot anymore, but I have a lot of equipment already!". Doesn't sound normal either !

How about making it available depending on a certain number of equipment owned by the user? The feature is about reset equipment, not levels, so it feels better. Should it be a number? Like 50 pieces it's 2 gems and 100 it's free? Or based on a percentage, as you keep adding more equipment on a regular basis? I think this direction would make more sense, than basing it on the levels, but that's my point of view :)

**Comment by Alys** [comment]
@Arsnael 
We typically don't care about abuse of features using Fix Character Values. In the case of a player rebirthing then deciding they want the fresh start to include having no gear, we'd encourage them to use FCV if the unlock condition was levels.

Unlocking / making it free based on number / percent of gear is an interesting idea! I'm on the fence about that or the Ultimate Gear achievement idea. There's been no discussion here about that since the issue was logged so I'm not sure anyone else has a solid opinion. 
The more gear that's released, the less relevant the achievement becomes so that might be a point in favour of using percent of gear instead.

**Comment by Arsnael** [comment]
@Alys : The ultimate gear of achievement of the current class could be yes, even if not really difficult to obtain. Well for now it's not a problem, I spend bits by bits on the code so it's rather slow, so if the mind changes around things still in discussion it should be easy to update during process :)

**Comment by Arsnael** [comment]
@beffymaroo No problem ! thanks for the resize, i will be able to replace my ugly resize with this one in the code :)

**Comment by citrusella** [comment]
I know this is a month ago, but on the subject of unlock conditions I'd really rather it be levels myself (or *either* levels or equipment? dunno how that would work), because I enjoy and would want to replicate old rebirth behavior and am concerned the other condition being the only metric would lead to it not being available at the same time under certain circumstances. And even though it's not really a focus of what was talked about, it's not like it's *more* impervious to FCV either (you could just add gold to buy equipment to unlock the achievement, unless you need equipment from multiple classes, which starts feeling a little pay-to-play on some level).

**Comment by Alys** [comment]
@citrusella makes a good point. Also, unlocking it based on only the player's level would be easier to code,
We could make the feature unlock at level 50 for now, and then if there's significant demand for other unlock conditions later, we could reconsider it.

@Arsnael How do you feel about that? Or have you already created code for unlocking that works differently than just considering the level?

**Comment by Arsnael** [comment]
@Alys : No problem. I just raised the issue while coding so that we have time to talk about it. So while nothing has been decided I kept the first decision in the code, which is unlock at lvl 50 (2 gems) and free at lvl 100. So no change for me if you want to go that way :)

**Comment by Arsnael** [comment]
I've been quite slow these days as  I'm quite busy with other matters but the code is more or less there... Just need to fix some bugs, adjust the images, add a battery of tests, etc

**Comment by Alys** [comment]
> I kept the first decision in the code, which is unlock at lvl 50 (2 gems) and free at lvl 100. So no change for me if you want to go that way

Perfect! We'll go that way.

> I've been quite slow these days as I'm quite busy with other matters but the code is more or less there... Just need to fix some bugs, adjust the images, add a battery of tests, etc

No worries, thanks for letting us know!

**Comment by Ieahleen** [comment]
Can I suggest an add on to the Orb of Rebirth description that says that if you want to use the empty the armoire feature you need to do that before the Orb of Rebirth?
Or maybe an extra object that would do both things?
Something for people with memory/attention trouble that want to both use the Orb of Rebirth and Empty the Armoire features and need to remember to do them in the right order (or the permission to send them to the Report a Bug guild (; )

**Comment by Alys** [comment]
> Can I suggest an add on to the Orb of Rebirth description that says that if you want to use the empty the armoire feature you need to do that before the Orb of Rebirth?

@Ieahleen Oh yes, excellent idea!!! I hadn't thought of that. You're right that it would be something that would trip people up.
I'm not opposed to an extra object but it would take more time to create if approved by the staff so for now I'm adding a item to the list in the top post for adjusting the Rebirth description.

**Comment by Arsnael** [comment]
@Ieahleen : yes that was one of my concerns as well for trying to find an other way than levels. I will try to add some description to it. But feel free to give me your exact copy of it if you have the words in mind :)

**Comment by Arsnael** [comment]
Hi ! I did a PR. I still have some stuff to tests so it's not completely ready yet (hence the WIP) but it's more or less finished, so you can start checking it if you want :)

**Comment by Ieahleen** [comment]
Can I point a thing on items with a 0G price?
There are various check-in incentives items that have a 0G price but have stats that are pretty high, I am sure that a lot of players that want to reset their inventory would also like to repurchase those (and maybe they value a bit more than 0G but that may be a thing to talk about somewhere else)
You can use the Empty the Armory Achievment and you can still find yourself with equipment to have +16/+17 on each attribute soon after

**Comment by Alys** [comment]
@Ieahleen Ah yes, that's a good point.

@Arsnael You might want to hold off on changing the code for a couple of days while we think about this.

**Comment by Arsnael** [comment]
Alright sure no problem :) I still need to add more tests anyway so I will try to focus on that instead when I have a bit of time

**Comment by Alys** [comment]
I'm not sure if the staff would want the check-in incentive items to have their price changed, but it would certainly fix the problem of emptying the armory and still having high-stat gear. Maybe those items were set to zero gold simply because there was no need to buy them to get them initially? I think it wouldn't be inconsistent if they did have a gold cost after that, so that they could be lost due to death or armory-emptying and then bought back. There's other gear that you can get for free (from quests) that you then can buy back with non-zero gold if you lose it. @SabreCat @beffymaroo What do you think?

I definitely agree that this shouldn't be a blocker. We could implement the Empty the Armory feature once it's reviewed and approved, and then later tweak either the feature or the items, depending on feedback.

**Comment by Arsnael** [comment]
Ah I see there is some updates on the messages around that too. So do I need to update that?

**Comment by Alys** [comment]
@Arsnael  [If the staff disagree with any of this, go with what they say]

 Regarding the text on that Trello card (good job on noticing it btw!) :

_"Has collected all the gear for at least one class and has emptied their armory X time(s)."_ - That would have been written back when we were thinking that getting an Ultimate Gear Achievement would be the unlock condition for Empty the Armory. I still like that we're unlocking it at level 50 here, for all the reasons we've discussed above.
The other texts would likely have been written at the same time so I think they're not necessarily updates on the text you have in your PR. 

However I think "Key to the Armory" is probably better than "Armory key" for `emptyArmoryName` because it's consistent with "Key to the Kennels".

For the revised Orb of Rebirth text (in `rebirthPop`), I like that your version uses the phrase "reset your equipment" because that makes it very clear, which I think is important there - we don't want people to be uncertain about what that message means when they're about to use Rebirth.
At the end of that phrase, it's probably better to use "Key to the Armory" rather than "Empty the Armory" because "Key..." is what they'll be seeing on the Market page.

**Comment by Alys** [comment]
PR https://github.com/HabitRPG/habitica/pull/10826 has been tested by a few people and they've given some feedback. I've added it to the top post in this issue to keep all the requirements in one place but my edits and additions are marked with EDIT/ADD and the date (2019-02-12). Here's a summary of the main points (see the top post for full details about all of them):

- A new name is needed because "Armory" was confused with "Armoire".
- The confirmation screen should warn that that all non-free gear will be removed.
- The achievement title and text might need changes.
- The locking / unlocking behaviour might need to be reconsidered.
- Seasonal Shop should not show the gear available for purchase with gold. (I haven't tested this one to see if it's still happening because the Shop is currently closed.)
- Staff will change zero-cost stats-providing equipment to give it a gold cost.

**Comment by citrusella** [comment]
> A new name is needed because "Armory" was confused with "Armoire"

Hmm... Key to the Closet? (I changed empty to key because I like alliteration, but I could see people thinking it'd be related to the kennel keys if key was part of its name. Or maybe not. IDK.)

**Comment by Alys** [comment]
I like Key to the Closet. I think it's beneficial to reuse "Key" for this to help the players understand it. Key to the Kennels removes Pets and Mounts, Key to the Closet removes equipment.

Other ideas are still welcome. :)

**Comment by Joseph67843** [comment]
"Closet key" does have an existing pop cultural meaning, but I don't think it would cause confusion.

https://tvtropes.org/pmwiki/pmwiki.php/Main/ClosetKey

**Comment by brightbold** [comment]
How about Key to the Wardrobe? It loses the nice alliteration, but retains the idea that we use  "key" for removing things, and I like it that wardrobe is an older word than closet, so it sounds more Habitican to me.

**Comment by beffymaroo** [comment]
Commenting to note this is on my radar! I can work on some of the text changes needed, other stuff will need more discussion with the team, I think. :)

**Comment by saraolson** [comment]
alrighty! so the team just have a discussion about some of the lingering questions around this feature and have come to some conclusions we're happy with:

**The name:**
We like 'Key to the Wardrobe'! It sounds fantastical and brings up memories of the lion, the witch, and the wardrobe which is right in habitica's spirit.

**Login Incentive gear:**
We'd like to assign gold prices to this gear based on the login incetive day you received it! So if you got a piece of gear on your 320th login, it costs 320 gold. If you got it on your 2nd login, it costs 2 gold. We thought this would be a nice call-back to remembering your habitica journey and an easy way to pick gold amounts.

**Using Rebirth + This item**
There was an issue where we had to warn users to use this key before rebirth because it would go away when they were bumped back to level 1. To avoid this, we'd like to check if a user is level 50 _or_ if they have the rebirth achievement. Then if they use rebirth and decide a few levels later they want to clear our their gear, they can still use this key because of the achievement check. (Along with this, we're not going to hide the key after they get the achievement and use it once. If they'd like to buy it again and empty out their gear earlier, they're welcome to.)

I think that covers everything. We're excited to start prepping for this feature's release!

**Comment by Arsnael** [comment]
I'm busy lately but promise to check it out when I have some time. Thanks team for reviewing and clarifying the requirements ! :)

**Comment by shanaqui** [comment]
@Arsnael Are you still interested in working on this? If so, please let us know!

**Comment by Arsnael** [comment]
Hi @shanaqui ! I kinda am but it's quite a big feature, and I lack too much the time for it lately, deeply sorry about it. On top of that, the code I did back then is probably completely outdated.

If someone else wants to tackle it, I have no problem with that !

**Comment by shanaqui** [comment]
@Arsnael Alright, for now I'll put it back to Help Wanted and if you have the time again, you can let us know!

**Comment by veeeeeee** [comment]
We're putting this feature on hold for now, pending resources to rethink the UX interaction.
